#!/usr/bin/env python3
"""Scaffold an empty SIGA-shaped Claude Code plugin for a new simulator.

Creates the directory tree, `.claude-plugin/plugin.json`, empty files at the
expected paths, and a starter `ADAPTATION_LOG.md`. The `siga-adapt` skill then
drives the actual content adaptation against the reference GEOS plugin.

Usage:
    python scaffold.py --simulator openfoam --target /path/to/plugin_openfoam

The target directory must not already contain a `.claude-plugin/plugin.json`
(refuse to overwrite). Pass `--force` to allow overwriting an existing
scaffold (the script never deletes user-authored content; it only writes the
files listed below).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Files the scaffold writes. Anything not in this list is left alone.
SCAFFOLD_FILES = [
    ".claude-plugin/plugin.json",
    "ADAPTATION_LOG.md",
    "README.md",
    "skills/{slug}-rag/SKILL.md",
    "scripts/{slug}_rag_mcp.py",
    "scripts/{slug}_lint_mcp.py",
    "hooks/verify_outputs.py",
    "hooks/verify_input_post_write.py",
    "hooks/hooks.json",
    "{SIM}_PRIMER_minimal.md",
    "{SIM}_PRIMER_lint.md",
]


def _slugify(name: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "-", name.strip().lower()).strip("-")
    if not s:
        raise ValueError(f"simulator name {name!r} produced empty slug")
    return s


def _expand(template: str, slug: str, sim_upper: str) -> str:
    return template.format(slug=slug, SIM=sim_upper)


def _plugin_json(slug: str, simulator: str) -> dict:
    return {
        "name": f"{slug}-plugin",
        "version": "0.1.0",
        "description": (
            f"SIGA plugin for {simulator}: RAG + lint MCP + primer + "
            "end-of-turn verifier. Generated by siga-factory."
        ),
        "author": {"name": "TBD"},
        "license": "MIT",
        "keywords": ["claude-code", "plugin", "siga", simulator.lower()],
    }


def _placeholder_body(rel_path: str, slug: str, sim_upper: str, simulator: str) -> str:
    """Return placeholder content for each scaffold file."""
    if rel_path.endswith("ADAPTATION_LOG.md"):
        return _adaptation_log(simulator)
    if rel_path.endswith("README.md"):
        return _readme(slug, simulator)
    if rel_path.endswith("hooks/hooks.json"):
        return _hooks_json()
    if rel_path.endswith("PRIMER_minimal.md"):
        return _primer_stub(simulator, "minimal")
    if rel_path.endswith("PRIMER_lint.md"):
        return _primer_stub(simulator, "lint")
    if rel_path.endswith("SKILL.md"):
        return _skill_stub(slug, simulator)
    if rel_path.endswith("_rag_mcp.py"):
        return _rag_mcp_stub(slug, simulator)
    if rel_path.endswith("_lint_mcp.py"):
        return _lint_mcp_stub(slug, simulator)
    if rel_path.endswith("hooks/verify_outputs.py"):
        return _verify_outputs_stub(slug, sim_upper, simulator)
    if rel_path.endswith("hooks/verify_input_post_write.py"):
        return _verify_post_write_stub(slug, sim_upper, simulator)
    return f"# TODO: populate {rel_path} for {simulator}\n"


def _adaptation_log(simulator: str) -> str:
    return (
        f"# {simulator} adaptation log\n\n"
        "Filled in by the `siga-adapt` skill as it walks the four components.\n\n"
        "## 1. RAG\n_(pending)_\n\n"
        "## 2. Lint / validator\n_(pending)_\n\n"
        "## 3. Memory (primer)\n_(pending)_\n\n"
        "## 4. Self-refinement (Stop hook)\n_(pending)_\n"
    )


def _readme(slug: str, simulator: str) -> str:
    return (
        f"# {slug}-plugin\n\n"
        f"SIGA plugin for **{simulator}**. Generated by siga-factory; the\n"
        "`siga-adapt` skill fills in the components against a reference\n"
        "implementation (the GEOS plugin).\n\n"
        "## Loading\n\n"
        "```bash\n"
        "claude --plugin-dir .\n"
        "```\n\n"
        "Inside Claude Code: `/reload-plugins`.\n\n"
        "## Components (status filled in by the adaptation skill)\n\n"
        "- [ ] RAG MCP\n"
        "- [ ] Lint MCP + PostToolUse hook\n"
        "- [ ] Primer (minimal + lint variants)\n"
        "- [ ] End-of-turn verifier (Stop hook)\n"
    )


def _hooks_json() -> str:
    return json.dumps(
        {
            "description": "TODO: fill in after adapting verify_outputs / verify_input_post_write.",
            "hooks": {
                "Stop": [
                    {
                        "matcher": "",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/verify_outputs.py",
                                "timeout": 30,
                            }
                        ],
                    }
                ],
                "PostToolUse": [
                    {
                        "matcher": "Write|Edit|MultiEdit",
                        "hooks": [
                            {
                                "type": "command",
                                "command": "python3 ${CLAUDE_PLUGIN_ROOT}/hooks/verify_input_post_write.py",
                                "timeout": 15,
                            }
                        ],
                    }
                ],
            },
        },
        indent=2,
    ) + "\n"


def _primer_stub(simulator: str, variant: str) -> str:
    return (
        f"# {simulator} Primer ({variant})\n\n"
        f"TODO: replace this stub with a real primer for {simulator}.\n\n"
        "Structure to follow (from the GEOS reference primer):\n\n"
        "## Where things live (inside the container)\n\n"
        "- TODO: examples directory\n"
        "- TODO: docs directory\n"
        "- TODO: workspace inputs directory\n\n"
        "## Top-level skeleton\n\n"
        "TODO: paste the canonical empty input file here.\n\n"
        "## Recommended workflow\n\n"
        "1. TODO\n"
    )


def _skill_stub(slug: str, simulator: str) -> str:
    return (
        "---\n"
        f"name: {slug}-rag\n"
        f"description: Use when answering {simulator} input-file or schema "
        "questions with the plugin-provided RAG MCP tools.\n"
        "---\n\n"
        f"TODO: adapt the geos-rag SKILL.md text to {simulator}.\n"
    )


def _rag_mcp_stub(slug: str, simulator: str) -> str:
    return (
        "# /// script\n"
        "# dependencies = [\n"
        '#   "chromadb>=1.0.0,<2",\n'
        '#   "mcp>=1.0.0,<2",\n'
        "# ]\n"
        "# ///\n"
        f'"""MCP server exposing {simulator} ChromaDB RAG search tools.\n\n'
        "Adapt scripts/geos_rag_mcp.py from the reference plugin. Keep the\n"
        "three-collection navigator/technical/schema structure (drop schema\n"
        f"if {simulator} has no schema-spec corpus and document that in\n"
        "ADAPTATION_LOG.md).\n"
        '"""\n'
        "raise NotImplementedError('Run the siga-adapt skill to fill this in.')\n"
    )


def _lint_mcp_stub(slug: str, simulator: str) -> str:
    return (
        "# /// script\n"
        "# dependencies = [\n"
        '#   "mcp>=1.0.0,<2",\n'
        "# ]\n"
        "# ///\n"
        f'"""MCP server exposing the {simulator} validator as a callable tool.\n\n'
        "Adapt scripts/xmllint_mcp.py from the reference plugin. Wrap the\n"
        f"native {simulator} validator subprocess; expose one tool named\n"
        f"validate_{slug}_input(path: str) -> str.\n"
        '"""\n'
        "raise NotImplementedError('Run the siga-adapt skill to fill this in.')\n"
    )


def _verify_outputs_stub(slug: str, sim_upper: str, simulator: str) -> str:
    return (
        "#!/usr/bin/env python3\n"
        f'"""Stop-hook end-of-turn verifier for {simulator} input-file tasks.\n\n'
        "Adapt hooks/verify_outputs.py from the reference plugin. Env-var\n"
        f"namespace: {sim_upper}_HOOK_*.\n"
        '"""\n'
        "raise NotImplementedError('Run the siga-adapt skill to fill this in.')\n"
    )


def _verify_post_write_stub(slug: str, sim_upper: str, simulator: str) -> str:
    return (
        "#!/usr/bin/env python3\n"
        f'"""PostToolUse hook: parse {simulator} input files after Write|Edit|MultiEdit.\n\n'
        "Adapt hooks/verify_xml_post_write.py from the reference plugin.\n"
        '"""\n'
        "raise NotImplementedError('Run the siga-adapt skill to fill this in.')\n"
    )


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--simulator", required=True, help="Display name, e.g. 'OpenFOAM'")
    ap.add_argument("--target", required=True, type=Path, help="Path for the new plugin")
    ap.add_argument("--force", action="store_true", help="Overwrite scaffold files if present")
    args = ap.parse_args()

    simulator = args.simulator.strip()
    slug = _slugify(simulator)
    sim_upper = re.sub(r"[^A-Z0-9]+", "_", simulator.upper()).strip("_") or slug.upper().replace("-", "_")
    target: Path = args.target.expanduser().resolve()

    plugin_manifest = target / ".claude-plugin" / "plugin.json"
    if plugin_manifest.exists() and not args.force:
        print(f"refusing to overwrite existing plugin at {plugin_manifest}; pass --force", file=sys.stderr)
        return 2

    written = []
    skipped = []
    for template in SCAFFOLD_FILES:
        rel = _expand(template, slug=slug, sim_upper=sim_upper)
        path = target / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if path.exists() and not args.force:
            skipped.append(rel)
            continue
        if rel == ".claude-plugin/plugin.json":
            path.write_text(json.dumps(_plugin_json(slug, simulator), indent=2) + "\n")
        else:
            path.write_text(_placeholder_body(rel, slug=slug, sim_upper=sim_upper, simulator=simulator))
        written.append(rel)

    print(f"Scaffolded {target}")
    print(f"  simulator: {simulator}")
    print(f"  slug:      {slug}")
    print(f"  env-prefix:{sim_upper}_HOOK_*")
    print(f"  wrote ({len(written)}):")
    for rel in written:
        print(f"    + {rel}")
    if skipped:
        print(f"  skipped ({len(skipped)}, pass --force to overwrite):")
        for rel in skipped:
            print(f"    - {rel}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
